services:
  postgres:
    image: postgres:16.1
    container_name: postgres2
    ports:
      - 6500:5432
    env_file:
      - ./.env
    volumes:
      - ./.store/postgres:/var/lib/postgresql/data
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - postgres

  go_app:
    image: golang:latest
    container_name: go_app
    working_dir: /app
    volumes:
      - ./go_app:/app
    ports:
      - 8080:8080
