services:
  postgres:
    image: postgres:16.1
    container_name: postgres2
    ports:
      - 6500:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=golang-gorm
    volumes:
      - ./.store/postgres:/var/lib/postgresql/data
  proxy:
    image: nginx
    volumes:
        - type: bind
          source: ./nginx.conf
          target: /etc/nginx/conf.d/default.conf
          read_only: true
    ports:
      - 80:80

  api:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: api
    environment:
        - POSTGRES_HOST=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password123
        - POSTGRES_DB=golang-gorm
        - POSTGRES_PORT=5432
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - postgres
